services:
  ros2:
    container_name: dora-ros
    build: 
      context: .
      target: dev

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - dora-vol:/opt/ros/kilted
    
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=/tmp/runtime-root
      - LIBGL_ALWAYS_SOFTWARE=0

    devices:
      - /dev/dri:/dev/dri

    tty: true

    network_mode: host
    ipc: host

volumes:
  dora-vol:

