version: '3'
services:
  ros2:
    container_name: dora-ros

    tty: true
    build: .

    network_mode: host

    # device_cgroup_rules:
    #   - 'c 188:* rmw'

    devices:
       - "/dev/ttyUSB0:/dev/ttyUSB0"
       # TODO: usb port for nucleo
      #  - "/dev/ttyUSB0:/dev/ttyTHS1"

    environment:
      - DISPLAY
