version: '3'
services:
  ros2:
    container_name: dora-ros
    image: ghcr.io/legokor/dora-ros:latest

    tty: true

    network_mode: host

    # device_cgroup_rules:
    #   - 'c 188:* rmw'

    devices:
       - "/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0:/dev/ttyUSB0"

    environment:
      - DISPLAY
