version: '3'
services:
  ros2:
    container_name: dora-ros
    image: ghcr.io/legokor/dora-ros:latest

    tty: true

    network_mode: host

    # device_cgroup_rules:
    #   - 'c 188:* rmw'

    devices:
       - "/dev/ttyUSB0:/dev/ttyUSB0"
       # TODO: usb port for nucleo
      #  - "/dev/ttyUSB0:/dev/ttyTHS1"

    environment:
      - DISPLAY
