name: Build ros container

on:
  push:
    branches:
      - "**"
    paths:
      - .github/workflows/build-ros-container.yml
      - Dockerfile
      - ros2_ws/**/*
      - scripts/*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # needed for publishing to ghcr.io
    env:
      __DORA_CI_ACTION: build

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push base image
        uses: docker/build-push-action@v6
        with:
          target: base
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push rviz image
        uses: docker/build-push-action@v6
        with:
          target: rviz
          push: true
          tags: ghcr.io/${{ github.repository }}-rviz:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push dev image
        uses: docker/build-push-action@v6
        with:
          target: dev
          push: true
          tags: ghcr.io/${{ github.repository }}-dev:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
